name: call reusable

on:
    push:
        branches: 
            - master

jobs:
    fist-job:
        runs-on: ubuntu-latest
        steps:
            - name: first step
              run: echo "fist step"
    deploy:
        needs: fist-job
        uses: ./.github/workflows/14-reusable.yml