name: 16 composite

on:
    push:
        branches: 
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v2
            - name: hello
              id: hello
              uses: ./.github/actions/my-action
              with: 
                name: Luke
            - name: outval
              run: echo ${{ steps.hello.outputs.out }}
    js:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v2
            - name: JS Action
              uses: ./.github/actions/my-js-action